version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
